//visible, collidable, oncreate, onbreak, breakable, requiredItem, multipleTextures
game.blockTypes = {
  dirt: [true, true, function(){}, function(){}, 0.7, ["*"], false],
  plant: [true, true, function(){}, function(){}, 1, ["*"], false],
  stone: [true, true, function(){}, function(){}, 4, ["wood_pickaxe", "stone_pickaxe", "pickaxe"], false],
  wood: [true, true, function(){}, function(){}, 1.5, ["*"], false],
  mud: [true, false, function(){}, function(){}, 0.3, ["*"], false],
  world_barrier: [false, true, function(){}, function(){}, 10, ["*"], false],
  tree: [true, false, function(){var this_ = this; var pos = new THREE.Vector3(0, 0, 0).copy(this.block.position); setTimeout(function (){this_.delete(true); setTimeout(function() {game.generation.tree(pos.x, pos.y, pos.z); game.UI.sound("plant1");}, 100)}, 5000);}, function (){}, 0.01, ["*"], false],
  bricks: [true, true, function(){}, function(){}, 3.5, ["wood_pickaxe", "stone_pickaxe", "pickaxe"], false],
  leaves: [true, true, function(){if(Math.random()*100 > 80){new game.item("tree", this.inventory)} else if(Math.random()*100 > 80){new game.item("apple", this.inventory)}}, function(){}, 0.5, ["*"], false],
  fat: [true, true, function(){}, function(){}, 0.3, ["*"], false],
  stonebricks: [true, true, function(){}, function(){}, 3.5, ["wood_pickaxe", "stone_pickaxe", "pickaxe"]],
  planks: [true, true, function(){}, function(){}, 1.5, ["*"], false],
  lava: [true, false, function(){}, function(){}, 100, ["*"], false],
  iron_ore: [true, true, function(){new game.item("iron", this.inventory)}, function(){}, 4.5, ["stone_pickaxe", "pickaxe"], false],
  diamond_ore: [true, true, function(){new game.item("diamond", this.inventory)}, function(){}, 5, ["pickaxe"], false],
  diamond_block: [true, true, function(){}, function(){}, 5, ["pickaxe"], false],
  chest: [true, true, function(){this.inventory.delete(); new game.inventory(this, 7); new game.item("chest", this.inventory)}, function(){}, 1, ["*"], true],
};